---
version: '3.7'

services:
  database:
    image: 'mysql:5'
    command:
      - '--local_infile=0'
      - '--log-error-verbosity=1'
      - '--max-allowed-packet=32M'
      - '--sql-mode=STRICT_ALL_TABLES'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - 'backend'
    volumes:
      - 'mysql:/var/lib/mysql'

  nginx:
    depends_on:
      - 'web'
    image: 'nginx:stable'
    networks:
      - 'frontend'
    ports:
      - '80:80'
    volumes:
      - './support/docker/nginx.conf:/etc/nginx/nginx.conf'

  web:
    build: './support/docker'
    depends_on:
      - 'database'
    entrypoint:
      - 'sh'
      - '-c'
      - |
        # Apply storage upgrades.
        /usr/local/src/phabricator/bin/storage upgrade --force

        docker-php-entrypoint \
          -d error_log=stderr \
          -d opcache.revalidate_freq=0 \
          -d opcache.validate_timestamps=1 \
          --fpm-config /usr/local/etc/php/php-fpm.conf \
          --nodaemonize \
          --allow-to-run-as-root
    environment:
      PHABRICATOR_DOMAIN: 'phabricator.local'
      PHABRICATOR_ENV: 'docker'
      PHABRICATOR_MYSQL_HOST: 'database'
      PHABRICATOR_MYSQL_USER: 'root'
    expose:
      - 8080
    networks:
      - 'backend'
      - 'frontend'
    volumes:
      - '.:/usr/local/src/phlab'
      - './support/docker/config.php:/usr/local/src/phabricator/conf/docker.conf.php'
      - './support/docker/php-fpm.conf:/usr/local/etc/php/php-fpm.conf'

      # Supporting repositories.
      - '../arcanist:/usr/local/src/arcanist'
      - '../libphutil:/usr/local/src/libphutil'
      - '../phabricator:/usr/local/src/phabricator'

      # Prevent `../phabricator/conf/local/` from being mounted.
      - '/usr/local/src/phabricator/conf/local'

networks:
  backend: {}
  frontend: {}

volumes:
  mysql: {}
