---
version: '3.7'

x-common: &phabricator
  depends_on:
    - 'bootstrap'
  environment:
    PHABRICATOR_DOMAIN: 'phabricator.local'
    PHABRICATOR_ENV: 'docker'
    PHABRICATOR_MYSQL_HOST: 'database'
    PHABRICATOR_MYSQL_USER: 'root'
  networks:
    - 'backend'
  volumes:
    - '.:/usr/local/src/phlab'
    - './support/docker/config.php:/usr/local/src/phabricator/conf/docker.conf.php'

    # Supporting repositories.
    - '../arcanist:/usr/local/src/arcanist'
    - '../libphutil:/usr/local/src/libphutil'
    - '../phabricator:/usr/local/src/phabricator'

    # Prevent `../phabricator/conf/local` from being mounted.
    - '/usr/local/src/phabricator/conf/local'

    # NOTE: This file is only needed by the `web` service, but there's currently
    # no way to merge lists in YAML (see https://github.com/yaml/yaml/issues/48).
    # Instead of duplicating the list of volumes across multiple services, just
    # mount the PHP-FPM configuration in all services.
    - './support/docker/php-fpm.conf:/usr/local/etc/php-fpm.conf'

services:
  bootstrap:
    <<: *phabricator
    build: './support/docker/worker'
    depends_on:
      - 'database'
    command:
      - 'upgrade'
      - '--force'
    entrypoint:
      - '/usr/local/src/phabricator/bin/storage'

  database:
    image: 'mysql:5'
    command:
      - '--local_infile=0'
      - '--log-error-verbosity=1'
      - '--max-allowed-packet=32M'
      - '--sql-mode=STRICT_ALL_TABLES'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - 'backend'
    volumes:
      - 'mysql:/var/lib/mysql'

  nginx:
    depends_on:
      - 'web'
    image: 'nginx:stable'
    networks:
      - 'frontend'
    ports:
      - '80:80'
    volumes:
      - './support/docker/nginx.conf:/etc/nginx/nginx.conf'

  web:
    <<: *phabricator
    build: './support/docker/web'
    networks:
      - 'backend'
      - 'frontend'

  worker:
    <<: *phabricator
    build: './support/docker/worker'
    entrypoint:
      - 'sh'
      - '-c'
      - |
        # Send logs to stderr (see https://worp.one/docker-symlink-your-log-files-to-stdout-and-stderr/).
        ln --symbolic /proc/1/fd/2 /var/log/daemons.log

        /usr/local/src/phabricator/bin/phd start

        # Keep the container running (see http://bigdatums.net/2017/11/07/how-to-keep-docker-containers-running/).
        tail --follow /dev/null

networks:
  backend: {}
  frontend: {}

volumes:
  mysql: {}
