<?php

return [
  'darkconsole.always-on'         => true,
  'darkconsole.enabled'           => true,
  'environment.append-paths'      => ['/usr/lib/git-core'],
  'files.enable-imagemagick'      => true,
  'load-libraries'                => ['phlab/src'],
  'metamta.default-address'       => 'noreply@'.getenv('PHABRICATOR_DOMAIN'),
  'metamta.reply-handler-domain'  => getenv('PHABRICATOR_DOMAIN'),
  'mysql.host'                    => getenv('PHABRICATOR_MYSQL_HOST'),
  'mysql.pass'                    => getenv('PHABRICATOR_MYSQL_PASSWORD') ?: null,
  'mysql.user'                    => getenv('PHABRICATOR_MYSQL_USER'),
  'phabricator.base-uri'          => sprintf('http://%s:%d', getenv('PHABRICATOR_DOMAIN'), getenv('PHABRICATOR_HTTP_PORT')),
  'phabricator.developer-mode'    => true,
  'phabricator.show-prototypes'   => true,
  'phabricator.timezone'          => 'Etc/UTC',
  'phd.log-directory'             => '/var/log',
  'phlab.maniphest.status-notes'  => [
    'name' => 'Status Notes',
    'placeholder' => 'Add more context on the status of the ticket',
  ],
  'phlab.maniphest.substatus'     => [
    'name' => 'Substatus',
    'options' => [
      'none' => null,
      'needsinfo' => 'Needs User Info',
      'investigating' => 'Investigating',
      'requirespmdecision' => 'Requires PM Decision',
      'requiresdesign' => 'Requires Design',
      'fordevelopment' => 'For Development',
      'indevelopment' => 'In Development',
      'codereview' => 'For Code Review',
      'fortesting' => 'For Testing',
      'forrelease' => 'For Release',
      'released' => 'Released',
      'blocked' => 'Blocked',
    ],
  ],
  'pygments.enabled'              => true,
  'repository.default-local-path' => '/var/repo',
];
