<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(),
  'symbols' => array(),
  'requires' => array(),
  'packages' => array(),
);
