<?php

/**
 * This file is automatically generated. Use 'bin/celerity map' to rebuild it.
 *
 * @generated
 */
return array(
  'names' => array(
    'css/phui/phui-form.css' => 'daa52323',
  ),
  'symbols' => array(
    'phui-form-css' => 'daa52323',
  ),
  'requires' => array(),
  'packages' => array(),
);
