<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'Composer' => 'infrastructure/Composer.php',
    'HeraldHipChatNotificationAction' => 'applications/herald/extension/HeraldHipChatNotificationAction.php',
    'HipChatClient' => 'infrastructure/HipChatClient.php',
    'HipChatConfigOptions' => 'applications/config/option/HipChatConfigOptions.php',
    'PhlabAWSFileStorageEngine' => 'applications/files/engine/PhlabAWSFileStorageEngine.php',
    'PhlabConfigOptions' => 'applications/config/option/PhlabConfigOptions.php',
    'PhlabLibraryTestCase' => '__tests__/PhlabLibraryTestCase.php',
  ),
  'function' => array(),
  'xmap' => array(
    'Composer' => 'Phobject',
    'HeraldHipChatNotificationAction' => 'HeraldAction',
    'HipChatClient' => 'Phobject',
    'HipChatConfigOptions' => 'PhabricatorApplicationConfigOptions',
    'PhlabAWSFileStorageEngine' => 'PhabricatorFileStorageEngine',
    'PhlabConfigOptions' => 'PhabricatorApplicationConfigOptions',
    'PhlabLibraryTestCase' => 'PhutilLibraryTestCase',
  ),
));
