<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'CreatePolicyConduitAPIMethod' => 'conduit/CreatePolicyConduitAPIMethod.php',
    'DiffusionPreCommitRepositoryProjectsMatchesUserProjectsHeraldField' => 'applications/diffusion/herald/DiffusionPreCommitRepositoryProjectsMatchesUserProjectsHeraldField.php',
    'FreelancerGoogleAuthRegistrationListener' => 'applications/auth/event/FreelancerGoogleAuthRegistrationListener.php',
    'HeraldRocketChatNotificationAction' => 'applications/herald/extension/HeraldRocketChatNotificationAction.php',
    'PhabricatorBot' => 'applications/chatlog/bot/PhabricatorBot.php',
    'PhabricatorBotFeedNotificationHandler' => 'applications/chatlog/bot/handler/PhabricatorBotFeedNotificationHandler.php',
    'PhabricatorBotHandler' => 'applications/chatlog/bot/handler/PhabricatorBotHandler.php',
    'PhabricatorBotLogHandler' => 'applications/chatlog/bot/handler/PhabricatorBotLogHandler.php',
    'PhabricatorBotObjectNameHandler' => 'applications/chatlog/bot/handler/PhabricatorBotObjectNameHandler.php',
    'PhabricatorChatbotChannel' => 'applications/chatlog/bot/target/PhabricatorChatbotChannel.php',
    'PhabricatorChatbotChannelTestCase' => 'applications/chatlog/bot/target/__tests__/PhabricatorChatbotChannelTestCase.php',
    'PhabricatorChatbotMessage' => 'applications/chatlog/bot/PhabricatorChatbotMessage.php',
    'PhabricatorChatbotMessageTestCase' => 'applications/chatlog/bot/__tests__/PhabricatorChatbotMessageTestCase.php',
    'PhabricatorChatbotTarget' => 'applications/chatlog/bot/target/PhabricatorChatbotTarget.php',
    'PhabricatorChatbotUser' => 'applications/chatlog/bot/target/PhabricatorChatbotUser.php',
    'PhabricatorChatbotUserTestCase' => 'applications/chatlog/bot/target/__tests__/PhabricatorChatbotUserTestCase.php',
    'PhabricatorHipChatProtocolAdapter' => 'applications/chatlog/bot/adapter/PhabricatorHipChatProtocolAdapter.php',
    'PhabricatorProtocolAdapter' => 'applications/chatlog/bot/adapter/PhabricatorProtocolAdapter.php',
    'PhlabAmazonSESMailImplementationAdapter' => 'applications/metamta/adapter/PhlabAmazonSESMailImplementationAdapter.php',
    'PhlabLibraryTestCase' => '__tests__/PhlabLibraryTestCase.php',
    'PhlabPatchList' => 'infrastructure/storage/patch/PhlabPatchList.php',
    'PhlabS3FileStorageEngine' => 'applications/files/engine/PhlabS3FileStorageEngine.php',
    'RocketChatClient' => 'infrastructure/RocketChatClient.php',
    'RocketChatConfigOptions' => 'applications/config/option/RocketChatConfigOptions.php',
  ),
  'function' => array(),
  'xmap' => array(
    'CreatePolicyConduitAPIMethod' => 'ConduitAPIMethod',
    'DiffusionPreCommitRepositoryProjectsMatchesUserProjectsHeraldField' => 'DiffusionPreCommitRefHeraldField',
    'FreelancerGoogleAuthRegistrationListener' => 'PhabricatorEventListener',
    'HeraldRocketChatNotificationAction' => 'HeraldAction',
    'PhabricatorBot' => 'PhabricatorDaemon',
    'PhabricatorBotFeedNotificationHandler' => 'PhabricatorBotHandler',
    'PhabricatorBotHandler' => 'Phobject',
    'PhabricatorBotLogHandler' => 'PhabricatorBotHandler',
    'PhabricatorBotObjectNameHandler' => 'PhabricatorBotHandler',
    'PhabricatorChatbotChannel' => 'PhabricatorChatbotTarget',
    'PhabricatorChatbotChannelTestCase' => 'PhutilTestCase',
    'PhabricatorChatbotMessage' => 'Phobject',
    'PhabricatorChatbotMessageTestCase' => 'PhutilTestCase',
    'PhabricatorChatbotTarget' => 'Phobject',
    'PhabricatorChatbotUser' => 'PhabricatorChatbotTarget',
    'PhabricatorChatbotUserTestCase' => 'PhutilTestCase',
    'PhabricatorHipChatProtocolAdapter' => 'PhabricatorProtocolAdapter',
    'PhabricatorProtocolAdapter' => 'Phobject',
    'PhlabAmazonSESMailImplementationAdapter' => 'PhabricatorMailImplementationPHPMailerLiteAdapter',
    'PhlabLibraryTestCase' => 'PhutilLibraryTestCase',
    'PhlabPatchList' => 'PhabricatorSQLPatchList',
    'PhlabS3FileStorageEngine' => 'PhabricatorFileStorageEngine',
    'RocketChatClient' => 'Phobject',
    'RocketChatConfigOptions' => 'PhabricatorApplicationConfigOptions',
  ),
));
